USE ROLE ACCOUNTADMIN;

-- Using ACCOUNTADMIN, create a new role for this exercise and grant to applicable users
CREATE OR REPLACE ROLE FS_API_ROLE;
GRANT ROLE FS_API_ROLE to USER <YOUR_USER>;

-- create our virtual warehouse
CREATE OR REPLACE WAREHOUSE FS_API_WH AUTO_SUSPEND = 60;

GRANT ALL ON WAREHOUSE FS_API_WH TO ROLE FS_API_ROLE;

-- Next create a new database and schema,
CREATE OR REPLACE DATABASE FS_API_DATABASE;
CREATE OR REPLACE SCHEMA FS_API_SCHEMA;

GRANT OWNERSHIP ON DATABASE FS_API_DATABASE TO ROLE FS_API_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL SCHEMAS IN DATABASE FS_API_DATABASE TO ROLE FS_API_ROLE COPY CURRENT GRANTS;
